-- Migration 00045: Add unified spread mode to film_scenes
--
-- is_unified_spread: when true, the scene uses ONE spread-level Kling video
--   instead of separate right-page / left-page videos. The spread video
--   spans both pages as a continuous visual background.
--
-- spread_video_path: storage path inside the films/ bucket for the unified
--   spread MP4 generated by Kling. NULL = not yet generated.
--   Cleared automatically when is_unified_spread is toggled.
ALTER TABLE public.film_scenes
  ADD COLUMN IF NOT EXISTS is_unified_spread  BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS spread_video_path  TEXT;
